# 04 numpy
## 4.1 安装
```bash
$pip install numpy
```
## 4.2 数组对象（ndarray)

In [3]:
# 导入numpy
import numpy as np

In [22]:
# 一维数组
one_d = np.array([1, 2, 3]) 
one_d2 = np.arange(6)
print(one_d, one_d2)

[1 2 3] [0 1 2 3 4 5]


In [18]:
# 多维数组
two_d = np.array([[1, 2, 3], [4, 5, 6]])
print(two_d)

three_d = np.array([[[1,1,1],[2,2,2]],[[1,1,1],[2,2,2]]])
print(three_d)

[[1 2 3]
 [4 5 6]]
[[[1 1 1]
  [2 2 2]]

 [[1 1 1]
  [2 2 2]]]


In [19]:
# 最小维度
min_dimension = np.array([1,2,3], ndmin=3)
print(min_dimension)

[[[1 2 3]]]


In [20]:
# 数组元素的数据类型
array_type = np.array([1,2,3], dtype=complex)
print(array_type)

[1.+0.j 2.+0.j 3.+0.j]
