# 04 numpy
## 4.1 安装
```bash
$pip install numpy
```
## 4.2 数组对象（ndarray)

In [1]:
# 导入numpy
import numpy as np

In [18]:
# 一维数组
one_d = np.array([1, 2, 3]) 
one_d2 = np.arange(6)
one_d3 = np.array((4, 5, 6))
print(one_d, one_d2, one_d3, sep='\n')

[1 2 3]
[0 1 2 3 4 5]
[4 5 6]


In [10]:
# 多维数组
two_d = np.array([[1, 2, 3], [4, 5, 6]])
print(two_d)

three_d = np.array([[[1,1,1],[2,2,2]],[[1,1,1],[2,2,2]]])
print(three_d)

[[1 2 3]
 [4 5 6]]
[[[1 1 1]
  [2 2 2]]

 [[1 1 1]
  [2 2 2]]]


## 4.2 数组属性
属性 | 含义
:-: | :-:
dtype| 元素类型
size| 数组元素的总个数
shape| 数组的形状，如：n行m列的矩阵就会返回（n, m)
itemsize| 每个元素的大小
ndim| 数组的维度
nbytes| 数组中的所有数据消耗掉的字节数

In [24]:
# Array properties
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])

print(type(a)) # >>><class 'numpy.ndarray'>
print('dtype:\t', a.dtype) 
print('size:\t', a.size) 
print('shape:\t', a.shape) 
print('itemsize:\t', a.itemsize) 
print('ndim:\t', a.ndim) 
print('nbytes:\t', a.nbytes) 

<class 'numpy.ndarray'>
dtype:	 int32
size:	 25
shape:	 (5, 5)
itemsize:	 4
ndim:	 2
nbytes:	 100


In [4]:
# 最小维度
min_dimension = np.array([1,2,3], ndmin=3)
print(min_dimension)

[[[1 2 3]]]


In [5]:
# 数组元素的数据类型
array_type = np.array([1,2,3], dtype=complex)
print(array_type)

[1.+0.j 2.+0.j 3.+0.j]


In [52]:
# 改变数组大小
x = np.array([[1, 2, 3],[4, 5, 6]])
print('修改前', x, sep='\n')
x.shape = (3,2)
print('修改后', x, sep='\n')

# 或者使用reshape() 函数
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2)  
print(b)
# reshape()会重新生成结果，不会影响原来的数组
print(a)

修改前
[[1 2 3]
 [4 5 6]]
修改后
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


## 4.3 新建数组

In [30]:
x = np.empty([3,2], dtype = int) 
print(x)

[[0 1]
 [2 3]
 [4 5]]


In [31]:
# 默认为浮点数
x = np.zeros(5) 
print(x)
 
# 设置类型为整数
y = np.zeros((5,), dtype = np.int) 
print(y)
 
# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [34]:
# 默认为浮点数
x = np.ones(5) 
print(x)

x = np.ones((5,5))
print(x)

# 自定义类型
x = np.ones([2,2], dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1]
 [1 1]]


In [36]:
x = np.full((2,2), 6)
print(x)

[[6 6]
 [6 6]]


In [37]:
# 新建一个n行n列的对角线为1 的矩阵
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [38]:
# 新建一个元素值为0-1的随机数组
x = np.random.random((3,4,3))
print(x)

[[[0.10639703 0.64172491 0.52474239]
  [0.96867856 0.07525236 0.70211413]
  [0.27090539 0.9583324  0.15231759]
  [0.07705065 0.73127792 0.03463946]]

 [[0.41069097 0.26980781 0.03144871]
  [0.86281176 0.38722614 0.21468678]
  [0.38549161 0.20245727 0.53254607]
  [0.13309459 0.96445312 0.41392928]]

 [[0.53358954 0.19797112 0.99741946]
  [0.71913043 0.60679427 0.22847322]
  [0.20459656 0.3508732  0.21972064]
  [0.55786914 0.06059451 0.81863818]]]
